apiVersion: argoproj.io/v1aplha1
kind: application
metadata:
  name: suse-py-actions
  namespace: argocdb
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config
    repoURL: https://github.com/shashwatkare/suse-py
    targetRevision: HEAD
  syncPolicy: {}
